plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf:
    ios:
      description: Use ios cliconf to run command on Cisco IOS platform
      name: ios
      version_added: 1.0.0
  connection: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    ios_acl_interfaces:
      description: ACL interfaces resource module
      name: ios_acl_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_acls:
      description: ACLs resource module
      name: ios_acls
      namespace: ''
      version_added: 1.0.0
    ios_banner:
      description: Manage multiline banners on Cisco IOS devices
      name: ios_banner
      namespace: ''
      version_added: 1.0.0
    ios_bgp:
      description: Configure global BGP protocol settings on Cisco IOS.
      name: ios_bgp
      namespace: ''
      version_added: 1.0.0
    ios_command:
      description: Run commands on remote devices running Cisco IOS
      name: ios_command
      namespace: ''
      version_added: 1.0.0
    ios_config:
      description: Manage Cisco IOS configuration sections
      name: ios_config
      namespace: ''
      version_added: 1.0.0
    ios_facts:
      description: Collect facts from remote devices running Cisco IOS
      name: ios_facts
      namespace: ''
      version_added: 1.0.0
    ios_interface:
      description: (deprecated, removed after 2022-06-01) Manage Interface on Cisco
        IOS network devices
      name: ios_interface
      namespace: ''
      version_added: 1.0.0
    ios_interfaces:
      description: Interfaces resource module
      name: ios_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_l2_interface:
      description: (deprecated, removed after 2022-06-01) Manage Layer-2 interface
        on Cisco IOS devices.
      name: ios_l2_interface
      namespace: ''
      version_added: 1.0.0
    ios_l2_interfaces:
      description: L2 interfaces resource module
      name: ios_l2_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_l3_interface:
      description: (deprecated, removed after 2022-06-01) Manage Layer-3 interfaces
        on Cisco IOS network devices.
      name: ios_l3_interface
      namespace: ''
      version_added: 1.0.0
    ios_l3_interfaces:
      description: L3 interfaces resource module
      name: ios_l3_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_lacp:
      description: LACP resource module
      name: ios_lacp
      namespace: ''
      version_added: 1.0.0
    ios_lacp_interfaces:
      description: LACP interfaces resource module
      name: ios_lacp_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_lag_interfaces:
      description: LAG interfaces resource module
      name: ios_lag_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_linkagg:
      description: Manage link aggregation groups on Cisco IOS network devices
      name: ios_linkagg
      namespace: ''
      version_added: 1.0.0
    ios_lldp:
      description: Manage LLDP configuration on Cisco IOS network devices.
      name: ios_lldp
      namespace: ''
      version_added: 1.0.0
    ios_lldp_global:
      description: LLDP resource module
      name: ios_lldp_global
      namespace: ''
      version_added: 1.0.0
    ios_lldp_interfaces:
      description: LLDP interfaces resource module
      name: ios_lldp_interfaces
      namespace: ''
      version_added: 1.0.0
    ios_logging:
      description: Manage logging on network devices
      name: ios_logging
      namespace: ''
      version_added: 1.0.0
    ios_ntp:
      description: Manages core NTP configuration.
      name: ios_ntp
      namespace: ''
      version_added: 1.0.0
    ios_ospfv2:
      description: OSPFv2 resource module
      name: ios_ospfv2
      namespace: ''
      version_added: 1.0.0
    ios_ping:
      description: Tests reachability using ping from Cisco IOS network devices
      name: ios_ping
      namespace: ''
      version_added: 1.0.0
    ios_static_route:
      description: (deprecated, removed after 2022-06-01) Manage static IP routes
        on Cisco IOS network devices
      name: ios_static_route
      namespace: ''
      version_added: 1.0.0
    ios_static_routes:
      description: Static routes resource module
      name: ios_static_routes
      namespace: ''
      version_added: 1.0.0
    ios_system:
      description: Manage the system attributes on Cisco IOS devices
      name: ios_system
      namespace: ''
      version_added: 1.0.0
    ios_user:
      description: Manage the aggregate of local users on Cisco IOS device
      name: ios_user
      namespace: ''
      version_added: 1.0.0
    ios_vlan:
      description: (deprecated, removed after 2022-06-01) Manage VLANs on IOS network
        devices
      name: ios_vlan
      namespace: ''
      version_added: 1.0.0
    ios_vlans:
      description: VLANs resource module
      name: ios_vlans
      namespace: ''
      version_added: 1.0.0
    ios_vrf:
      description: Manage the collection of VRF definitions on Cisco IOS devices
      name: ios_vrf
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.0.0
