---
name: code_coverage

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches: [ main ]

jobs:
  codecoverage:
    uses: roverflow/github_actions/.github/workflows/coverage_network_devices.yml@codecov
    with:
      collection_pre_install: >-
        git+https://github.com/ansible-collections/ansible.utils.git
        git+https://github.com/ansible-collections/ansible.netcommon.git
